export {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  TabsRoot,
  TabsListAdvanced,
  TabsTab,
  TabsPanel,
  TabsIndicator,
  type TabsProps,
  type TabsListProps,
  type TabsListPropsLegacy,
  type TabsTriggerProps,
  type TabsContentProps,
  type TabsRootProps,
  type TabsTabProps,
  type TabsPanelProps,
  type TabsIndicatorProps,
} from './Tabs';
export { default } from './Tabs';
